spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    social:
        facebook:
            appId: 1068557229922864
            appSecret: a8c5ac7b5da180c2f8e494d69fc5f883
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:h2:file:./spring-blog
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone : Asia/Seoul
#        deserialization:
#            unwrap-root-value: true
#        serialization:
#            wrap-root-value: true

logging:
    level:
        xyz.dddog.blog: DEBUG

server:
    error:
        whitelabel:
            enabled: false